#!/bin/sh

set -e

case "$1" in
    configure)
	if ! [ -d /etc/salt/eventsd_workers ]
	then
	    mkdir /etc/salt/eventsd_workers
	fi

        if ! [ -f /etc/salt/eventsd_workers/Minion_Return_Worker.py ]
	then
           zcat /usr/share/doc/salt-eventsd/eventsd_workers/Minion_Return_Worker.py.gz > /etc/salt/eventsd_workers/Minion_Return_Worker.py
	fi

        if ! [ -f /etc/salt/eventsd_workers/New_Job_Worker.py ]
	then
           zcat /usr/share/doc/salt-eventsd/eventsd_workers/New_Job_Worker.py.gz  > /etc/salt/eventsd_workers/New_Job_Worker.py
	fi
    ;;
esac

update-python-modules -a -f -v
update-rc.d salt-eventsd defaults

if [ $? -eq 0 ]
then
    echo "created start-up links"
else
    echo "failed to create start-up links, please create them yourself"
fi
echo ""
echo "INFO: NOT STARTING THE DAEMON. CONFIGURE IT FIRST!"
echo "INFO: see /etc/salt/eventsd for configuration."
echo "INFO: sample database-scheme to install can be found here: "
echo "INFO: /usr/share/doc/salt-eventsd/mysql-example.sql"
echo ""
