#!/bin/sh

set -e

#case "$1" in
#    configure)
#        if [ -f /etc/salt/eventsd.simple ]
#	then
#            mv /etc/salt/eventsd.simple /etc/salt/eventsd
#	fi
#	if ! [ -d /etc/salt/eventsd_workers ]
#	then
#	    mkdir /etc/salt/eventsd_workers
#	fi
#
#        if [ -f /usr/share/doc/salt-eventsd/eventsd_workers/Minion_Return_Worker.py.gz ]
#	then
#            zcat /usr/share/doc/salt-eventsd/eventsd_workers/Minion_Return_Worker.py.gz > /etc/salt/eventsd_workers/Minion_Return_Worker.py
#	fi
#
#        if [ -f /usr/share/doc/salt-eventsd/eventsd_workers/New_Job_Worker.py.gz ]
#	then
#            zcat /usr/share/doc/salt-eventsd/eventsd_workers/New_Job_Worker.py.gz  > /etc/salt/eventsd_workers/New_Job_Worker.py
#	fi
#
#	/usr/sbin/update-python-modules -f
#    ;;
#esac

update-rc.d salt-eventsd defaults

if [ $? -eq 0 ]
then
    echo "created start-up links"
else
    echo "failed to create start-up links, please create them yourself"
fi
